//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Session_id { get; set; }
        public int Session_AccountId { get; set; }
        public string Session_AppId { get; set; }
        public string Session_UserName { get; set; }
        public Nullable<System.DateTime> Session_StartTime { get; set; }
        public Nullable<System.DateTime> Session_LastActivityTime { get; set; }
        public Nullable<bool> Session_IsTerminated { get; set; }
        public Nullable<bool> Session_IsKilled { get; set; }
        public string Session_IPAddress { get; set; }
        public string Session_HostName { get; set; }
        public Nullable<int> Session_VersionNo { get; set; }
        public string Session_TransactionId { get; set; }
        public string Session_CreatedBy { get; set; }
        public Nullable<System.DateTime> Session_CreatedTime { get; set; }
        public string Session_LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> Session_LastUpdatedTime { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
